### ISSUE TITLE
Improve translations

### ISSUE THREAD

**Issue by skliarie** [tfroehlich82/koalixcrm#56]
Is there someone working on russian translation?
I might consider to volunteer to do one.

**Comment by skliarie** [comment]
The codebase is not accepting russian letters in text fields.. any attempt to enter ones yields warnings like these:
Warning at /en/products/create/
Incorrect string value: '\xD0\xBF\xD0\xBE\xD0\xB4...' for column 'item_title' at row 1

What could be done to suppress or fix these?

**Comment by tfroehlich82** [comment]
I will do some tests and let you know. There is no russian translation planned for now, but contributions are welcome.

**Comment by tfroehlich82** [comment]
I cannot reproduce this with the development version. All kyrilic signs seem to work fine. Can you please download the current master version and try again?
If you add ('ru', _('Russian')), to LANGUAGES tuple in settings.py (there are already two items for english and german) you should also see some already translated words.
