### ISSUE TITLE
TemplateDoesNotExist: smuggler/change_list.html

### ISSUE THREAD

**Issue by skliarie** [tfroehlich82/koalixcrm#60]
admin->crm_Core.Customers

TemplateDoesNotExist at /en/admin/crm_core/customer/

smuggler/change_list.html

Request Method: 	GET
Request URL: 	http://127.0.0.1:8000/en/admin/crm_core/customer/
Django Version: 	1.7.5
Exception Type: 	TemplateDoesNotExist
Exception Value: 	

smuggler/change_list.html

**Comment by tfroehlich82** [comment]
You need to install django-smuggler. Just run `pip install -r requirements.txt`again.
