### ISSUE TITLE
quotes view, purchaseorders views return 404

### ISSUE THREAD

**Issue by skliarie** [tfroehlich82/koalixcrm#61]
http://crm2.catchmedia.com/en/quotes/view/1/
http://crm2.catchmedia.com/en/purchaseorders/view/4/

**Comment by tfroehlich82** [comment]
This URLs doesn't exist yet. They should point to PDF. I'm currently working on some model improvements [refs #53], which will cause some heavy database changes. I'm also going to implement that feature with Ticket #53.
