### ISSUE TITLE
ImportError: No module named 'cartridge'

### ISSUE THREAD

**Issue by stevenyaga** [tfroehlich82/koalixcrm#69]
After i run pip install -r dev-requirements.txt, i get "ImportError: No module named 'cartridge'" when i run manage.py check. I am on Django 1.8 Python 2.7

**Comment by tfroehlich82** [comment]
can you please run 'pip list' and see if there is Cartridge listed? It has been tested with Django 1.8 and Python 2.7 32-Bit on Win, Ubuntu and Debian. Which OS are you using?
Can't reproduce this...

You can try to run 'pip install -U Cartridge' if it's not listed.
